### ISSUE TITLE
Change the name of "wdi-fundamentals," possibly to "origin"

### ISSUE THREAD

**Issue by jdmaresco** [generalassembly/fundamentals#13]
**From PJ (@h4w5):**

---

I'd like to propose that we change the name of the prework.

My understanding is that the goal of the prework is to introduce students to the language, so that they have a level of familiarity with:

- the language's basic syntax (so that there is a baseline for day one, when we begin teaching), 
- universal constructs common to programming (so that we can immediately begin building mental models to apply our understandings), and
- **a unified vocabulary and style** so that we can better create shared resources and experiences between cohorts.

That shared familiarity is a far more direct and achievable goal than "learning the fundamentals of the language." In fact, I believe that if one understands the fundamentals of a language, they've learned the language. Calling the prework "fundamentals" both oversells its importance, increases the scope of its contents (making it harder to manage), and undermines the role of classroom instruction.

I also think that the prework should act universally, and not be only applicable to WDI (even if this is the primary target). This means including the name "wdi" in it is either limiting or redundant.

JD has floated the term "**Origin**", which I think is a fine term. Does anyone have other suggestions or feelings about this?

---

Original Gitlab discussion:
![](https://www.dropbox.com/s/gqg38rp38cmtsp0/Screenshot%202015-04-15%2010.35.31.png?dl=1)

**Comment by jdmaresco** [comment]
This issue is a larger one related to Fundamentals as a product. We _could_ continue the discussion here, but I'm going to close this for now since it hasn't gotten any comments, and put it on the WDI roadmap as a bigger task, which involves a potential future migration to another non-Gitbook platform.

**Comment by h4w5** [comment]
Cool!
